on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_call:

name: Tests

jobs:
  tests:
    runs-on: ${{ matrix.runon }}
    
    strategy:
      matrix:
        runon:
          - "ubuntu-latest"
          - "windows-latest"
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - shell: bash
        run: |
          LM_BUILD_VERSION="TESTING $(git describe --always)"
          echo "LM_BUILD_VERSION=$LM_BUILD_VERSION"
          echo "LM_BUILD_VERSION=$LM_BUILD_VERSION" >> $GITHUB_ENV
      - name: run tests
        run: cargo test
