name: test checkout

on:
  pull_request:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - run: |
          git fetch --tags --force
          git tag -l --format='%(contents)' ${{ github.ref_name }}
  
  notify:
    uses: ./.github/workflows/release-notify.yml
    secrets:
      TELEGRAM_INFO_BOT_ID: ${{ secrets.TELEGRAM_INFO_BOT_ID }}
      TELEGRAM_INFO_CHANNEL_ID: "-1002079493269"
    with:
      message_prepend: "🤖 Lifeblood-Manager update ${{ github.ref_name }}!\n\n"
      message_body_command: "git tag -l --format='%(contents)' v0.2.0"
      message_append: "\n\nhttps://github.com/${{ github.repository}}/releases/tag/${{ github.ref_name }}\n\n#manager"

    needs: [ "test" ]