on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_call:

name: Tests

jobs:
  tests:
    runs-on: ${{ matrix.runon }}
    
    strategy:
      matrix:
        runon:
          - "ubuntu-latest"
          - "windows-latest"
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: run tests
        run: cargo test
